from tkinter import *
from tkinter import ttk

root = Tk()
root.title("Test")

root.columnconfigure(0, weight=1)
root.rowconfigure(0, weight=1)

frame_debug_bg_style = ttk.Style()
frame_debug_bg_style.configure("DebugBG.TFrame", background="pink")

main_frame = ttk.LabelFrame(root, text="Hello", style="DebugBG.TFrame")
main_frame.grid(column=0, row=0, sticky=(N, E, W, S))

label = ttk.Label(main_frame, text="HELLO HELLO HELLO HELLO HELLO\nHELLO HELLO HELLO HELLO HELLO\nHELLO HELLO HELLO HELLO HELLO\nHELLO HELLO HELLO HELLO HELLO\nHELLO HELLO HELLO HELLO HELLO\nHELLO HELLO HELLO HELLO HELLO\nHELLO HELLO HELLO HELLO HELLO\nHELLO HELLO HELLO HELLO HELLO\nHELLO HELLO HELLO HELLO HELLO\nHELLO HELLO HELLO HELLO HELLO\nHELLO HELLO HELLO HELLO HELLO\nHELLO HELLO HELLO HELLO HELLO\nHELLO HELLO HELLO HELLO HELLO\nHELLO HELLO HELLO HELLO HELLO\nHELLO HELLO HELLO HELLO HELLO\nHELLO HELLO HELLO HELLO HELLO\nHELLO HELLO HELLO HELLO HELLO\nHELLO HELLO HELLO HELLO HELLO\nHELLO HELLO HELLO HELLO HELLO\nHELLO HELLO HELLO HELLO HELLO\nHELLO HELLO HELLO HELLO HELLO\nHELLO HELLO HELLO HELLO HELLO\nHELLO HELLO HELLO HELLO HELLO\nHELLO HELLO HELLO HELLO HELLO\nHELLO HELLO HELLO HELLO HELLO\nHELLO HELLO HELLO HELLO HELLO\nHELLO HELLO HELLO HELLO HELLO\nHELLO HELLO HELLO HELLO HELLO\nHELLO HELLO HELLO HELLO HELLO\nHELLO HELLO HELLO HELLO HELLO\nHELLO HELLO HELLO HELLO HELLO\nHELLO HELLO HELLO HELLO HELLO\nHELLO HELLO HELLO HELLO HELLO\nHELLO HELLO HELLO HELLO HELLO\nHELLO HELLO HELLO HELLO HELLO\nHELLO HELLO HELLO HELLO HELLO\nHELLO HELLO HELLO HELLO HELLO\nHELLO HELLO HELLO HELLO HELLO\nHELLO HELLO HELLO HELLO HELLO\nHELLO HELLO HELLO HELLO HELLO\nHELLO HELLO HELLO HELLO HELLO\nHELLO HELLO HELLO HELLO HELLO\nHELLO HELLO HELLO HELLO HELLO\nHELLO HELLO HELLO HELLO HELLO\nHELLO HELLO HELLO HELLO HELLO\n")
label.grid(column=0, row=0, sticky=N)

root.mainloop()
